import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import { ArrowRightLeft, Loader2 } from 'lucide-react';
import MainLayout from '../../layouts/MainLayout';
import adminAPI from '../../api/admin.api';

export default function StudentMigrationPage() {
  const [classes, setClasses] = useState([]); const [form, setForm] = useState({ fromClassId: '', toClassId: '', session: '', term: 'Third Term' }); const [preview, setPreview] = useState(null); const [loading, setLoading] = useState(false);
  useEffect(() => { adminAPI.getClasses().then(({ data }) => setClasses(data.classes || [])).catch(() => toast.error('Unable to load classes')); }, []);
  const change = (key, value) => { setForm((current) => ({ ...current, [key]: value })); setPreview(null); };
  const makePreview = async () => { try { setLoading(true); const { data } = await adminAPI.previewMigration(form); setPreview(data.preview); } catch (error) { toast.error(error.response?.data?.message || 'Unable to prepare migration'); } finally { setLoading(false); } };
  const confirm = async () => { if (!preview || !window.confirm(`Move ${preview.affectedCount} student(s)? Historical results and attendance will remain unchanged.`)) return; try { setLoading(true); const { data } = await adminAPI.confirmMigration({ ...form, confirm: true }); toast.success(data.message); setPreview(null); } catch (error) { toast.error(error.response?.data?.message || 'Migration failed'); } finally { setLoading(false); } };
  return <MainLayout><div className="mx-auto max-w-4xl space-y-6"><div><h1 className="text-2xl font-bold text-slate-900">Student Migration</h1><p className="mt-1 text-sm text-slate-500">Promote a class or move selected learners without removing historical records.</p></div><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">From class<select className="mt-1 w-full rounded-lg border border-slate-300 p-2" value={form.fromClassId} onChange={(e) => change('fromClassId', e.target.value)}><option value="">Select source</option>{classes.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Move to<select className="mt-1 w-full rounded-lg border border-slate-300 p-2" value={form.toClassId} onChange={(e) => change('toClassId', e.target.value)}><option value="">Select destination</option>{classes.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Academic session<input className="mt-1 w-full rounded-lg border border-slate-300 p-2" placeholder="2026/2027" value={form.session} onChange={(e) => change('session', e.target.value)} /></label><label className="text-sm font-medium text-slate-700">Completed term<select className="mt-1 w-full rounded-lg border border-slate-300 p-2" value={form.term} onChange={(e) => change('term', e.target.value)}>{['First Term','Second Term','Third Term'].map((term) => <option key={term}>{term}</option>)}</select></label></div><button disabled={loading} onClick={makePreview} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{loading ? <Loader2 size={16} className="animate-spin" /> : <ArrowRightLeft size={16} />} Preview migration</button></section>{preview && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-bold text-slate-900">Confirm migration</h2><p className="mt-2 text-sm text-slate-700"><strong>{preview.affectedCount}</strong> learner(s) will move from <strong>{preview.fromClass.name}</strong> to <strong>{preview.toClass.name}</strong>. Their previous placement is retained in academic history.</p><div className="mt-4 max-h-56 overflow-auto rounded-lg border border-amber-200 bg-white">{preview.students.map((student) => <div key={student._id} className="border-b border-slate-100 px-4 py-2 text-sm text-slate-700">{student.fullname} <span className="text-slate-400">{student.registrationNumber}</span></div>)}</div><button disabled={loading} onClick={confirm} className="mt-4 rounded-lg bg-amber-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">Confirm and move students</button></section>}</div></MainLayout>;
}
